:PROPERTIES:
:ID:       58e5f7a4-15aa-4a1d-99ed-0f28843a00d6
:END:
#+title:      Spring 2026 HQI Synergy Day
#+date:       [2026-03-11 Wed 00:00]
#+identifier: 20260311T000000

* Logistics
:PROPERTIES:
:ID:       d80fdfe4-d96f-4712-930b-3210dddf6609
:END:
- Date :: March 11, 2026
- Location :: Salle Erdös, INRIA Paris, 48 rue Barrault, 75013 Paris
- Registration :: [[https://cryptpad.fr/form/#/2/form/view/13mHzGzX3h4FBwZ+LeM3+xO5HzhI9Rs3EVkWKeqeqDo/][form]]
- Tentative Program ::
  
| 08:30 - 08:55 | /Registration/                                   |                                      |
| 08:55 - 09:00 | /Welcome/                                        | Harold Ollivier (ENS-CNRS-INRIA)     |
| 09:00 - 09:25 | WP1 (Stack)                                      | Cyril Allouche (Bull)                |
| 09:30 - 09:55 | WP2 (Certified Compilation)                      | Mathieu Nguyen (CEA)                 |
| 10:00 - 10:25 | WP3 (optimization and ML)                        | Alex Grilo (SU-CNRS)                 |
| 10:30 - 10:50 | /Coffee Break/                                   |                                      |
| 10:50 - 11:15 | WP4 (Algorithms for many body physics)           | Pascal Tremblin (CEA)                |
| 11:20 - 11:45 | WP5 (Error correction and noise estimation)      | Cambyse Rouzé (INRIA)                |
| 11:50 - 12:15 | WP6 (Distributed and delegated QC)               | Damian Markham (SU-CNRS)             |
| 12:15 - 13:45 | /Lunch on your own/                              |                                      |
| 13:45 - 14:10 | [[id:05ab1db4-a94d-4b42-bc93-22c9a3ff6e2f][Learning and certification of local...]]           | Tim Möbus (U. Cambridge)             |
| 14:15 - 14:40 | [[id:4569a398-9336-4df5-9da7-b5c00d783623][Quantum Control and General...]]                   | Kathleen Barsse (INRIA)              |
| 14:45 - 15:10 | [[id:931cfedd-792c-4cfa-b2fd-179018874e9e][Composable privacy of networked...]]               | Naomi Solomons (SU-CNRS)             |
| 15:15 - 15:40 | [[id:8cbf050e-0413-4ad7-b7cb-6e58a9306e82][Stripe phases in strongly correlated electron...]] | Olivier Simard (X-Collège de Framce) |
| 15:45 - 16:05 | /Coffee Break/                                   |                                      |
| 16:05 - 16:30 | [[id:eaca9bf3-1de8-4d96-b062-63575d39e42b][Quantum error mitigation by...]]                   | Theo Saporiti  (UPSaclay-CEA)        |
| 16:35 - 17:00 | [[id:7ce01402-eb05-4ea4-b792-b528911eee3f][Self-concordant Schrödinger operators...]]         | Alex Grilo (SU-CNRS)                 |
| 17:05 - 17:30 | [[id:1c78abd0-0d8a-461e-828e-60142cefcbdd][Observing the weak breaking of...]]                | Alice Marché (UPSaclay-CNRS)         |

* Talks

** Learning and certification of local time-dependent quantum dynamics and noise (Tim Möbus)
:PROPERTIES:
:ID:       05ab1db4-a94d-4b42-bc93-22c9a3ff6e2f
:END:
Hamiltonian learning protocols are quickly establishing themselves as valuable tools to benchmark and verify quantum computers and simulators. However, virtually no rigorous protocols exist to learn time-dependent Hamiltonians and Lindbladians, despite their widespread applications. In this work, we address this gap and show how to learn the time-dependent evolution of a locally interacting $n$-qubit system arranged on a graph $\mathsf{G}$ of effective dimension $D$ by resorting only to the preparation of product Pauli eigenstates, evolution by the time-dependent generator for given times and measurements in product Pauli bases. We assume that the time-dependent parameters are well-approximated by functions in a known space of dimension $m$ and for which we can efficiently perform stable interpolation, say by polynomial functions. Our protocol outputs an expansion in that basis that approximates the parameters up to $\epsilon$ in an interval and only requires $\widetilde{\mathcal O} \big(\epsilon^{-2}\,\mathrm{poly}({m})\,\log(n\delta^{-1})\big)$ samples and $\mathrm{poly}({n,m})$ preprocessing and postprocessing to learn the parameters with probability of success $1-\delta$, making it highly scalable. Importantly, the scaling in the dimension $m$ is polynomial, whereas naive extensions of previous methods yield a dependency that is exponential in $m$. Like previous protocols for the time-independent case, ours is mostly based on estimating time derivatives of expectation values of various observables through interpolation techniques. We then obtain well-conditioned linear equations that allow us to evaluate the value of the time-dependent function for a local generator. However, whereas in the time-independent case it sufficed to only consider derivatives at time $t=0$, here we need to evaluate them at finite times while still being able to relate the derivatives to parameters of the evolution. Thus, besides dealing with technical intricacies related to the time-dependent case, our main innovation is to show how to combine Lieb-Robinson bounds, process shadows and semidefinite programs to estimate the parameters of the evolution efficiently at constant times. Along the way, we extend state-of-the-art Lieb-Robinson bounds on general graphs to the time-dependent, dissipative setting, a result of independent interest. As such, our protocol is a valuable tool to verify various state preparation procedures on quantum computers and simulators, such as adiabatic preparation, or to characterize time-dependent Markovian noise.

** Quantum Control and General Recursion beyond the Unitary Case (Kathleen Barsse)
:PROPERTIES:
:ID:       4569a398-9336-4df5-9da7-b5c00d783623
:END:
Coherent control, aka quantum control, is a central concept in quantum computing that is attracting increasing attention from both the quantum foundations and quantum software communities. Defining coherent control in the presence of recursion and measurement has long been known to be a major challenge. In particular, no-go results have been established for standard semantical domains like completely positive maps. We address this problem by introducing the first quantum programming language with recursion that allows for the coherent control of arbitrary quantum operations. We equip this language with both an operational and a denotational semantics that we prove to be adequate. To design these semantics, we show that combining coherent control, recursion, and measurement crucially requires describing the evolution of subprograms in the absence of input. To address this, the operational semantics takes into account a default evolution branch, while the denotational semantics uses the concept of coherent quantum operation, based on vacuum extensions. We strengthen the validity of our approach by developing an observational equivalence: two programs are equivalent if their probability of termination is the same in any context. The denotational semantics is shown to be fully abstract with respect to this observational equivalence.

** Stripe phases in strongly correlated electron systems: A slave-spin-1 approach toward spin-based quantum simulation (Olivier Simard)
:PROPERTIES:
:ID:       8cbf050e-0413-4ad7-b7cb-6e58a9306e82
:BACKLINKS: [[id:d80fdfe4-d96f-4712-930b-3210dddf6609][Logistics]]
:END:
Richard Feynman famously emphasized the inherently quantum mechanical nature of the world, arguing that quantum systems are best simulated using synthetic quantum devices. In this spirit, quantum many-body systems composed of strongly correlated fermions on a lattice have long been central to condensed-matter physics. These systems are notoriously challenging to solve, even with state-of-the-art numerical techniques, particularly in parameter regimes where competing or cooperating degrees of freedom operate at comparable energy and length scales. In this work, we introduce a spin-1 slave-particle approach to approximately treat interacting fermionic models at arbitrary electron doping in an efficient and economical way. Within this framework, the original charge and spin degrees of freedom are mapped onto effective pseudo-spin and pseudo-fermion sectors, respectively. These sectors are then handled using a self-consistent cluster mean-field method. We explore the resulting phase diagram under various conditions and observe the emergence of charge and spin stripe phases within this formalism. Notably, these stripe patterns arise as a consequence of the cluster mean-field treatment of the pseudo-particle sectors and were not identified in earlier slave-particle studies. Our results show qualitative agreement with more reliable numerical approaches and provide a concrete theoretical example of a complex fermionic many-body state that could be realistically implemented and investigated using spin-based quantum simulators, such as Rydberg-atom platforms.
** Quantum error mitigation by hierarchy-informed sampling: chiral dynamics in the Schwinger model
:PROPERTIES:
:ID:       eaca9bf3-1de8-4d96-b062-63575d39e42b
:BACKLINKS: [[id:d80fdfe4-d96f-4712-930b-3210dddf6609][Logistics]]
:END:
The phase diagram of QCD at finite densities remains numerically inaccessible by classical computations. Quantum computers, with their potential for exponential speedup, could overcome this challenge. However, their current physical implementations are affected by quantum noise. In this talk, I will introduce a novel quantum error mitigation technique based on an extended qubits BBGKY-like hierarchy. This mitigation scheme is applicable to any spin-chain quantum simulation, that is, whose Hamiltonian can be time-dependent and can encode arbitrary interactions among spins. The core idea of our method is to draw connected BBGKY equations from the hierarchy and use them to constrain a random sampling of possible mitigations. Our results indicate that the mitigation scheme, applied to simulations of the chiral magnetic effect in the (1+1)-Schwinger model, systematically and progressively improves the quality of the noisy measurements, as a larger selected portion of the BBGKY hierarchy constraints the mitigation.
** Self-concordant Schrödinger operators: spectral gaps and optimization without condition numbers (Alex Grilo)
:PROPERTIES:
:ID:       7ce01402-eb05-4ea4-b792-b528911eee3f
:BACKLINKS: [[id:d80fdfe4-d96f-4712-930b-3210dddf6609][Logistics]]
:END:
Spectral gaps play a fundamental role in many areas of mathematics, computer science, and physics. In quantum mechanics, the spectral gap of Schrödinger operators has a long history of study due to its physical relevance, while in quantum computing spectral gaps are an important proxy for efficiency, such as in the quantum adiabatic algorithm. Motivated by convex optimization, we study Schrödinger operators associated with self-concordant barriers over convex domains and prove non-asymptotic lower bounds on the spectral gap for this class of operators. Significantly, we find that the spectral gap does not display any condition-number dependence when the usual Laplacian is replaced by the Laplace--Beltrami operator, which uses second-order information of the barrier and hence can take the curvature of the barrier into account. As an algorithmic application, we construct a novel quantum interior point method that applies to arbitrary self-concordant barriers and shows no condition-number dependence. To achieve this we combine techniques from semiclassical analysis, convex optimization, and quantum annealing. 
** Composable privacy of networked quantum sensing (Naomi Solomons)
:PROPERTIES:
:ID:       931cfedd-792c-4cfa-b2fd-179018874e9e
:BACKLINKS: [[id:d80fdfe4-d96f-4712-930b-3210dddf6609][Logistics]]
:END:
Networks of sensors are a promising scheme to deliver the benefits of quantum technologies in coming years, offering enhanced precision and accuracy for distributed metrology through the use of large entangled states. Recent work has additionally explored the privacy of these schemes, meaning that local parameters can be kept secret while a joint function of these is estimated by the network. The abstract cryptography model, which represents protocols in terms of resources, can be used to show that the two proposed definitions of quasi-privacy are composable, which enables the protocol to be securely included as a sub-routine to other schemes. We will illustrate this using the example of estimating the mean of a set of parameters using GHZ states.
** Observing the weak breaking of conservation laws in a dipolar quantum spin chain (Alice Marché)
:PROPERTIES:
:ID:       1c78abd0-0d8a-461e-828e-60142cefcbdd
:BACKLINKS: [[id:d80fdfe4-d96f-4712-930b-3210dddf6609][Logistics]]
:END:
Integrability, one of the main technical theoretical tools for the analysis of models of physical setups, is not just a mathematical property: it has deep physical consequences. Integrable and non-integrable setups display qualitative different physical behaviours, related to the presence (or absence) of families of extensive conservation laws. In the presence of weak perturbations, a well-known dilemma takes place: is the system akin to a thoroughly non-integrable setup, or does it carry memory that integrability has been only weakly broken? In this theoretical and experimental collaboration we show that the weak breaking of conservation laws leaves a clear experimental fingerprint in a one-dimensional quantum spin chain of as few as 14 Rydberg atoms. Weak integrability breaking from interatomic dipolar couplings is directly detectable within experimentally accessible times in the dynamics of non-local observables. In particular, magnetization fluctuations are highly sensitive to the breaking of fragile conservation laws and exhibit anomalous growth, which we observe experimentally; similar signatures appear in a semilocal string observable. We establish Rydberg-atom arrays as a platform to test perturbative descriptions of quantum many-body dynamics with weak integrability breaking. Based on: https://arxiv.org/abs/2602.02251
** COMMENT Composable Verification in the Circuit-Model via Magic-Blindness (Sami Abdul Sater)
:PROPERTIES:
:ID:       b7aa124a-8b0a-4b23-9224-486185279b59
:END:
As quantum computing machines move towards the utility regime, it is essential that users are able to verify their delegated quantum computations with security guarantees that are (i) robust to noise, (ii) composable with other secure protocols, and (iii) exponentially stronger as the number of resources dedicated to security increases. Previous works that achieve these guarantees and provide modularity necessary to optimization of protocols to real-world hardware are most often expressed in the Measurement-Based Quantum Computation (MBQC) model. This leaves architectures based on the circuit model -- in particular those using the Magic State Injection (MSI) -- with fewer options to verify their computations or with the need to compile their circuits in MBQC leading to overheads.

This paper introduces a family of noise robust, composable and efficient verification protocols for Clifford + MSI circuits that are secure against arbitrary malicious behavior. This family contains the verification protocol of Broadbent (ToC, 2018), extends its security guarantees while also bridging the modularity gap between MBQC and circuit-based protocols, and reducing quantum communication costs. As a result, it opens the prospect of rapid implementation for near-term quantum devices.

Our technique is based on a refined notion of blindness, called magic-blindness, which hides only the injected magic states -- the sole source of non-Clifford computational power. This enables verification by randomly interleaving computation rounds with classically simulable, magic-free test rounds, leading to a trap-based framework for verification. As a result, circuit-based quantum verification attains the same level of security and robustness previously known only in MBQC. It also optimizes the quantum communication cost as transmitted qubits are required only at the locations of state injection. 
