#+BEGIN_COMMENT
.. title: Main activities
.. slug: index
.. date: 2021-08-16 10:53:53 UTC+02:00
.. tags: 
.. category: 
.. link: 
.. description: 
.. type: text

#+END_COMMENT
# +TITLE: Research Program
# +OPTIONS: toc:nil 

* Research
My research activity focuses on the interplay between application design and quantum computing architectures.

One application that we have been extensively developing is the delegation of quantum computations to third-party providers while maintaining security -- ie. privacy of the data and algorithm used, as well as integrity of the computation itself. Several approaches have been designed over the years for tackling this question. The one the team is working on is based on trapification of measurement based quantum computation. It is lightweight in the overhead at the client side -- only single qubit operations are required -- while most of the burden is taken care of by the server. To enable this approach it is nonetheless needed to have quantum communication between the client and the server.

Our latest protocol[fn:1] has enabled a drastic lowering of the requirements at the server's side to the point where it is now feasible to have small proof of concepts of verified quantum computations using existing devices. The constraints imposed by the noisy devices available have been taken care of by using classical amplification for the trap's detection sensitivity. We removed the burden of having a specific fault-tolerant encoding for this crucial part of the protocol. This allows a constant level of noise per run and removes all space overhead of the protocol -- converting it instead into a polynomial time overhead.

One of our future goals is to continue provide generic methods for reducing the overhead of these protocols and to enhance their usefulness for NISQ machines.

A connected research line that we follow is the use of measurement based quantum computating to overcome the difficulty of implementing protocols for secure multi-party quantum computations. We introduced a generic protocol[fn:2] with low overhead for the clients and the server, while allowing all but one party to be malicious while retaining security. Turning such protocol into experimentally implementable is one of our next goals.

Other topics that we are currently investigating with a similar approach -- integration of physical constraints into the design of new protocols and algorithms -- are
- quantum machine learning
- benchmarking and noise characterization

I've been also contributing to the understanding of the emergence of classical objective properties out of quantum theory in various settings, such as many-body physics[fn:3]

* QuantumTech@INRIA

I head the QuantumTech Program launched by INRIA in 2021 to materialize its quantum expertise started more than 20 years ago on decoherence and quantum error correction. One of the objectives for this program is to accompany the deployment of the National Strategy for Quantum Technologies through the participation of INRIA teams to several research and development projects. The program provides coordination for the research teams at the national as well as international level. 

Several teams are naturally part of QuantumTech@INRIA as they are dedicated to quantum information such as [[https://www.inria.fr/en/cosmiq][COSMIQ]], [[https://www.inria.fr/en/mocqua][MOCQUA]], [[https://www.inria.fr/en/qinfo][QInfo]], [[https://www.inria.fr/en/quacs][QUACS]], [[https://www.inria.fr/en/quantic][QUANTIC]]. Expertise is also being built-up in collaboration with several classical INRIA teams that can benefit from quantum algorithms.

* Papers

<html>
<head>
<title>Dr. Nate's Page of accomplishments</title>
<script type="text/javascript">
<!--
var arxiv_authorid = "yourauthorid";
//--></script>
<style type="text/css">
div.arxivfeed {margin-bottom: 5px; width:700px;}
</style>
<script type="text/javascript" src="https://arxiv.org/js/myarticles.js">
</script>
</head>
<body>
<h1>Nate Rules!</h1>
<p>Stuff goes here</p>
<div id="arxivfeed"></div>
</body>
</html>


* Footnotes

[fn:1]
"Securing Quantum Computations in the NISQ Era", Elham Kashefi, Dominik Leichtle, Luka Music, Harold Ollivier, PRX Quantum 2, 040302 (2021) https://journals.aps.org/prxquantum/abstract/10.1103/PRXQuantum.2.040302
[fn:2]
"Delegating Multi-Party Quantum Computations vs. Dishonest Majority in Two Quantum Rounds", Théodoros Kapourniotis, Elham Kashefi, Luka Music, Harold Ollivier http://www.arxiv.org/abs/2102.12949
[fn:3] "Emergence of Objectivity for Quantum Many-Body Systems", Harold Ollivier Entropy, 24(2), 277 (2022) https://www.mdpi.com/1099-4300/24/2/277
